package:
  name: arduino-cli
  version: "1.3.1"

source:
  path: .

build:
  number: 0

test:
  commands:
    - arduino-cli version

about:
  home: https://github.com/arduino/arduino-cli
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Arduino Command Line Interface
  description: |
    arduino-cli is an all-in-one solution that provides builder, boards/library manager, 
    uploader, discovery and many other tools needed to use any Arduino compatible board 
    and platform from command line or machine interfaces.
  doc_url: https://arduino.github.io/arduino-cli/
  dev_url: https://github.com/arduino/arduino-cli